version: '3.3'
services:
  orientDB:
    container_name: orient
    image: "orientdb:3.0.30"
    environment:
      - ORIENTDB_ROOT_PASSWORD=password
    volumes: 
     - /orientdb/databases
    ports:
      - '2480:2480'
      - '2424:2424'
    expose:
      - '2424'
  web:
      depends_on: 
        - orientDB
      build: .
      ports:
        - "5000:5000"
      links:
          - "orientDB"
      volumes:
        - .:/code